services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./strapi:/app
    ports:
      - "3000:1337"
    environment:
      NODE_ENV: production
    command: ["sleep", "infinity"]