{{- $name := "db-backup" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}
  namespace: {{ template "cacao.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
  annotations:
    {{- (include "cacao.globalAnnotations" . ) | nindent 4 }}
spec:
  schedule: {{ default "0 2 * * *" .Values.pgbackup.schedule }} # This will run the job daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: {{ default "ghcr.io/neitofr/cacao-toolbox:latest" .Values.pgbackup.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
              command: ["/bin/sh", "-c"]
              args:
                - sleep infinity
              volumeMounts:
                - name: s3cfg
                  mountPath: /root/.s3cfg
                  subPath: s3cfg
                - name: script
                  mountPath: /root/script.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
            - name: s3cfg
              configMap:
                name: {{ include "cacao.fullname" . }}-s3cfg-config
            - name: script
              configMap:
                name: {{ include "cacao.fullname" . }}-db-backup-script
