{{- if .Values.upload_backup.enabled -}}
{{- $name := "upload-backup" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}
  namespace: {{ template "cacao.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
  annotations:
    {{- (include "cacao.globalAnnotations" . ) | nindent 4 }}
spec:
  schedule: {{ default "0 */4 * * *" .Values.upload_backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: upload-backup
              image: {{ default "ghcr.io/neitofr/cacao-toolbox:latest" .Values.pgbackup.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: {{ include "cacao.fullname" . }}-{{ $name }}-config
              command: ["sh", "/tmp/script.sh"]
              volumeMounts:
                - name: s3cfg
                  mountPath: /root/.s3cfg
                  subPath: s3cfg
                - name: script
                  mountPath: /tmp/script.sh
                  subPath: backup.sh
                - mountPath: {{ .Values.upload_backup.config.SRC_DIR }}
                  name: strapi-uploads
          restartPolicy: OnFailure
          {{- (include "cacao.imagePullSecrets" .) | nindent 10 }}
          volumes:
            - name: s3cfg
              configMap:
                name: {{ include "cacao.fullname" . }}-{{ $name }}-s3cfg-config
            - name: script
              configMap:
                name: {{ include "cacao.fullname" . }}-{{ $name }}-script
            - name: strapi-uploads
              persistentVolumeClaim:
                claimName: {{ include "cacao.fullname" . }}-strapi-uploads
{{- end -}}