{{- if .Values.pgbackup.enabled -}}
{{- $name := "db-backup" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  DB_HOST: {{ default "localhost" .Values.pgbackup.config.DB_HOST | toString | b64enc }}
  DB_PORT: {{ default "5432" .Values.pgbackup.config.DB_PORT | toString | b64enc }}
  DB_USER: {{ .Values.pgbackup.config.DB_USER | toString | b64enc }}
  DB_PASSWORD: {{ .Values.pgbackup.config.DB_PASSWORD | toString | b64enc }}
  ENCRPYPTION_KEY: {{ .Values.pgbackup.config.ENCRPYPTION_KEY | toString | b64enc }}
  DBS_TO_BACKUP: {{ .Values.pgbackup.config.DBS_TO_BACKUP | toString | b64enc }}
  S3_URL: {{ .Values.pgbackup.config.S3_URL | toString | b64enc }}
  S3_BUCKET: {{ (default .Values.pgbackup.config.S3_URL .Values.pgbackup.config.S3_BUCKET)  | toString | b64enc }}
  S3_BUCKET_URL: {{ (default .Values.pgbackup.config.S3_URL .Values.pgbackup.config.S3_BUCKET_URL)  | toString | b64enc }}
  S3_ACCESS_KEY: {{ .Values.pgbackup.config.S3_ACCESS_KEY | toString | b64enc }}
  S3_SECRET_KEY: {{ .Values.pgbackup.config.S3_SECRET_KEY | toString | b64enc }}
  S3_REGION: {{ .Values.pgbackup.config.S3_REGION | toString | b64enc }}
{{- end -}}