{{- $name := "strapi" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  HOST: {{ default .Values.deployments.strapi.config.HOST "0.0.0.0" }}
  PORT: {{ default .Values.deployments.strapi.config.PORT 1337 }}
  APP_KEYS: {{ .Values.deployments.strapi.config.APP_KEYS }}
  API_TOKEN_SALT: {{ .Values.deployments.strapi.config.API_TOKEN_SALT }}
  ADMIN_JWT_SECRET: {{ .Values.deployments.strapi.config.ADMIN_JWT_SECRET }}
  TRANSFER_TOKEN_SALT:
    {{ .Values.deployments.strapi.config.TRANSFER_TOKEN_SALT }}
  DATABASE_CLIENT:
    {{ default .Values.deployments.strapi.config.DATABASE_CLIENT "postgres" }}
  DATABASE_HOST: {{ .Values.deployments.strapi.config.DATABASE_HOST }}
  DATABASE_PORT: {{ .Values.deployments.strapi.config.DATABASE_PORT }}
  DATABASE_NAME:
    {{ default .Values.deployments.strapi.config.DATABASE_NAME "cacao" }}
  DATABASE_USERNAME:
    {{ default .Values.deployments.strapi.config.DATABASE_USERNAME "cacao" }}
  DATABASE_PASSWORD: {{ .Values.deployments.strapi.config.DATABASE_PASSWORD }}
  DATABASE_SSL:
    {{ default .Values.deployments.strapi.config.DATABASE_SSL "false" }}
  JWT_SECRET: {{ .Values.deployments.strapi.config.JWT_SECRET }}
