{{- $name := "strapi" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  HOST: {{ default "0.0.0.0" .Values.deployments.strapi.config.HOST | b64enc }}
  PORT: {{ default 1337 .Values.deployments.strapi.config.PORT | toString | b64enc }}
  APP_KEYS: {{ .Values.deployments.strapi.config.APP_KEYS | b64enc }}
  API_TOKEN_SALT: {{ .Values.deployments.strapi.config.API_TOKEN_SALT | b64enc }}
  ADMIN_JWT_SECRET: {{ .Values.deployments.strapi.config.ADMIN_JWT_SECRET | b64enc }}
  TRANSFER_TOKEN_SALT: {{ .Values.deployments.strapi.config.TRANSFER_TOKEN_SALT | b64enc }}
  DATABASE_CLIENT: {{ default "postgres" .Values.deployments.strapi.config.DATABASE_CLIENT | b64enc }}
  DATABASE_HOST: {{ .Values.deployments.strapi.config.DATABASE_HOST | b64enc }}
  DATABASE_PORT: {{ .Values.deployments.strapi.config.DATABASE_PORT | toString |  b64enc }}
  DATABASE_NAME: {{ default "cacao" .Values.deployments.strapi.config.DATABASE_NAME | b64enc }}
  DATABASE_USERNAME: {{ default "cacao" .Values.deployments.strapi.config.DATABASE_USERNAME | b64enc }}
  DATABASE_PASSWORD: {{ .Values.deployments.strapi.config.DATABASE_PASSWORD | toString | b64enc }}
  DATABASE_SSL: {{ default "false" .Values.deployments.strapi.config.DATABASE_SSL | b64enc }}
  JWT_SECRET: {{ .Values.deployments.strapi.config.JWT_SECRET | b64enc }}