{{- $name := "strapi" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  HOST: {{ default .Values.deployments.strapi.config.HOST "0.0.0.0" | b64enc | quote }}
  PORT: {{ default .Values.deployments.strapi.config.PORT "1337" | b64enc | quote }}
  APP_KEYS: {{ .Values.deployments.strapi.config.APP_KEYS | b64enc | quote }}
  API_TOKEN_SALT: {{ .Values.deployments.strapi.config.API_TOKEN_SALT | b64enc | quote }}
  ADMIN_JWT_SECRET: {{ .Values.deployments.strapi.config.ADMIN_JWT_SECRET | b64enc | quote }}
  TRANSFER_TOKEN_SALT:
    {{ .Values.deployments.strapi.config.TRANSFER_TOKEN_SALT | b64enc | quote }}
  DATABASE_CLIENT:
    {{ default .Values.deployments.strapi.config.DATABASE_CLIENT "postgres" | b64enc | quote }}
  DATABASE_HOST: {{ .Values.deployments.strapi.config.DATABASE_HOST | b64enc | quote }}
  DATABASE_PORT: {{ .Values.deployments.strapi.config.DATABASE_PORT | b64enc | quote }}
  DATABASE_NAME:
    {{ default .Values.deployments.strapi.config.DATABASE_NAME "cacao" | b64enc | quote }}
  DATABASE_USERNAME:
    {{ default .Values.deployments.strapi.config.DATABASE_USERNAME "cacao" | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.deployments.strapi.config.DATABASE_PASSWORD | b64enc | quote }}
  DATABASE_SSL:
    {{ default .Values.deployments.strapi.config.DATABASE_SSL "false" | b64enc | quote }}
  JWT_SECRET: {{ .Values.deployments.strapi.config.JWT_SECRET | b64enc | quote }}
