{{- $name := "strapi" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  HOST: {{ default .Values.deployments.strapi.config.HOST "0.0.0.0" | quote | b64enc }}
  PORT: {{ default .Values.deployments.strapi.config.PORT "1337" | quote | b64enc }}
  APP_KEYS: {{ .Values.deployments.strapi.config.APP_KEYS | quote | b64enc }}
  API_TOKEN_SALT: {{ .Values.deployments.strapi.config.API_TOKEN_SALT | quote | b64enc }}
  ADMIN_JWT_SECRET: {{ .Values.deployments.strapi.config.ADMIN_JWT_SECRET | quote | b64enc }}
  TRANSFER_TOKEN_SALT: {{ .Values.deployments.strapi.config.TRANSFER_TOKEN_SALT | quote | b64enc }}
  DATABASE_CLIENT: {{ default .Values.deployments.strapi.config.DATABASE_CLIENT "postgres" | quote | b64enc }}
  DATABASE_HOST: {{ .Values.deployments.strapi.config.DATABASE_HOST | quote | b64enc }}
  DATABASE_PORT: {{ .Values.deployments.strapi.config.DATABASE_PORT | quote | b64enc }}
  DATABASE_NAME: {{ default .Values.deployments.strapi.config.DATABASE_NAME "cacao" | quote | b64enc }}
  DATABASE_USERNAME: {{ default .Values.deployments.strapi.config.DATABASE_USERNAME "cacao" | quote | b64enc }}
  DATABASE_PASSWORD: {{ .Values.deployments.strapi.config.DATABASE_PASSWORD | quote | b64enc }}
  DATABASE_SSL: {{ default .Values.deployments.strapi.config.DATABASE_SSL "false" | quote | b64enc }}
  JWT_SECRET: {{ .Values.deployments.strapi.config.JWT_SECRET | quote | b64enc }}
