{{- if .Values.upload_backup.enabled -}}
{{- $name := "upload-backup" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}-config
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
type: Opaque
data:
  S3_URL: {{ .Values.upload_backup.config.S3_URL | toString | b64enc }}
  S3_BUCKET: {{ (default .Values.upload_backup.config.S3_URL .Values.upload_backup.config.S3_BUCKET)  | toString | b64enc }}
  S3_BUCKET_URL: {{ (default .Values.upload_backup.config.S3_URL .Values.upload_backup.config.S3_BUCKET_URL)  | toString | b64enc }}
  S3_ACCESS_KEY: {{ .Values.upload_backup.config.S3_ACCESS_KEY | toString | b64enc }}
  S3_SECRET_KEY: {{ .Values.upload_backup.config.S3_SECRET_KEY | toString | b64enc }}
  S3_REGION: {{ .Values.upload_backup.config.S3_REGION | toString | b64enc }}
  SRC_DIR: {{ .Values.upload_backup.config.SRC_DIR | toString | b64enc }}
  DEST_DIR: {{ .Values.upload_backup.config.DEST_DIR | toString | b64enc }}
{{- end -}}