apiVersion: v1
kind: Service
metadata:
  name: {{ include "cacao.fullname" . }}-strapi
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: strapi
spec:
  ports:
  - name: website
    port: {{ default 1337 .Values.service.port }}
    protocol: TCP
    targetPort: 1337
  selector:
    {{- (include "cacao.selectorLabels" .) | nindent 4 }}
    app.kubernetes.io/name: strapi
  type: ClusterIP
