{{- $name := "strapi" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cacao.fullname" . }}-{{ $name }}
  namespace: {{ include "cacao.namespace" . }}
  labels:
    {{- (include "cacao.commonLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  ports:
  - name: {{ $name }}
    port: {{ default 1337 .Values.services.strapi.port }}
    protocol: TCP
    targetPort: 1337
  selector:
    {{- (include "cacao.selectorLabels" .) | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
  type: ClusterIP
