apiVersion: v1
kind: Secret
metadata:
  name: strapi-dev-config
  namespace: default
type: Opaque
data:
  HOST:
  PORT:
  APP_KEYS:
  API_TOKEN_SALT:
  ADMIN_JWT_SECRET:
  TRANSFER_TOKEN_SALT:
  DATABASE_CLIENT:
  DATABASE_HOST:
  DATABASE_PORT:
  DATABASE_NAME:
  DATABASE_USERNAME:
  DATABASE_PASSWORD:
  DATABASE_SSL:
  JWT_SECRET: