apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: cacao-dev
  labels:
    app.kubernetes.io/instance: cacao-dev
    app.kubernetes.io/name: strapi
    app.kubernetes.io/part-of: cacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cacao-dev
      app.kubernetes.io/name: strapi
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cacao-dev
        app.kubernetes.io/name: strapi
        app.kubernetes.io/part-of: cacao
    spec:
      initContainers:
        - name: init-copy
          image: ghcr.io/neitofr/association-cacao/strapi:2024-11-03-v1
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp -r /app/* /mnt/app
          volumeMounts:
            - name: strapi-storage
              mountPath: /mnt/app
      containers:
        - name: strapi
          image: ghcr.io/neitofr/association-cacao/strapi:2024-11-03-v1
          envFrom:
            - secretRef:
                name: strapi-dev-config
          ports:
            - containerPort: 1337
          command: ["sleep", "infinity"]
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
          volumeMounts:
            - name: strapi-storage
              mountPath: /app
      volumes:
        - name: strapi-storage
          persistentVolumeClaim:
            claimName: strapi-dev-pvc
