{{- if .Values.pgbackup.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cacao.fullname" . }}-s3cfg-config
  namespace: {{ .Release.Namespace }}
data:
  s3cfg: |
    [default]
    access_key = $S3_ACCESS_KEY
    secret_key = $S3_SECRET_KEY
    host_base = $S3_URL
    host_bucket = $S3_BUCKET_URL
    use_https = True
    region = $S3_REGION
{{- end -}}