apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-cacao
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/neito-s-den/actions-runner:latest
      repository: NeitoFR/association-cacao
